"""add_progress_percent_to_uploads

Revision ID: e6f168c90ff8
Revises: 0002_schedule_execution
Create Date: 2026-08-18 23:16:04.355923
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e6f168c90ff8'
down_revision: Union[str, Sequence[str], None] = '0002_schedule_execution'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_schedules', 'last_executed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_schedules', sa.Column('last_executed_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
